### PR TITLE
Adding support for macOS (OSX)

### PR DESCRIPTION
**Pull request by douglowe**
I've added support for macOS - using an Automator script to run jupyter in a bash shell. Mostly the install script follows the same layout as for gnome, except that I've added a check for the path to the jupyter executable, as this sometimes can lie outside the conda environment directory (usually when it's been installed in the base environment, and then is reused for the current environment).

### CODE REVIEW

**Comment by ericpre** [comment]
@k8macarthur and @thomasaarholt, if I remember correctly both of you are mac users, could you please test and provide feedback or review?
I will test it over the week-end.

To test it, run the following:
```
pip install https://github.com/UoMResearchIT/start_jupyter_cm/archive/master.zip
start_jupyter_cm
```
And to remove the context menu:
```
start_jupyter_cm --remove
```

**Comment by k8macarthur** [comment]
I'm not quite sure want you want testing  but it seems to install and start without errors. 

```
Successfully built start-jupyter-cm
Installing collected packages: start-jupyter-cm
Successfully installed start-jupyter-cm-2.0.dev0
pool-7-76-zam859:~ macark$ start_jupyter_cm
Jupyter qtconsole here created.
Jupyter notebook here created.
pool-7-76-zam859:~ macark$ start_jupyter_cm
pool-7-76-zam859:~ macark$ start_jupyter_cm -- remove
usage: start_jupyter_cm [-h] [--remove] [--version]
start_jupyter_cm: error: unrecognized arguments: -- remove
pool-7-76-zam859:~ macark$ start_jupyter_cm --remove
Jupyter qtconsole here removed.
Jupyter notebook here removed.
pool-7-76-zam859:~ macark$ 
```

**Comment by douglowe** [comment]
That's great. Are you able to use the menu options to fire up the notebook and qtconsole too? (the readme explains how to do this: [https://github.com/UoMResearchIT/start_jupyter_cm](https://github.com/UoMResearchIT/start_jupyter_cm))

**Comment by douglowe** [comment]
I've removed the check for the jupyter executable pathway from the macOS code too.

**Comment by k8macarthur** [comment]
Screenshot 2019-09-27 at 15 25 46

**Comment by k8macarthur** [comment]
This is the error I get when trying to open a jupiter notebook from the right click menu.

**Comment by k8macarthur** [comment]
Scratch that. the qt console works fine. And trying on a different notebook/area I can get jupiter notebook to open too.

**Comment by douglowe** [comment]
Good to hear it's mostly working.

Are you able to reproduce the error you showed above? Was it when you tried to open a notebook file? If so, what was the file name you were opening?

**Comment by k8macarthur** [comment]
So the filename I tried to open which produce this error is entitled 'Wedge Analysis - EDX Cross Sections .ipynb' I'm guessing it's the hyphen that caused the problem...

**Comment by douglowe** [comment]
That is very useful info - thanks.

It's the spaces in the filename which are the problem - bash shell doesn't like these. Adding "" around the filename will fix this (forcing bash to read the text as one string, rather than splitting it up by the whitespace) - I'll adapt the script now.

**Comment by ericpre** [comment]
Thanks, this works as advertised and looks very good to me!
I have sent a PR https://github.com/UoMResearchIT/start_jupyter_cm/pull/1 to simplify the MacOSX image and make it easier to read - and it would save you disabling/uninstalling the other shortcuts to make this image.

In term of maintenance, if for some reasons, a new version of macosx breaks it, the way to go would be create a new script using automator and update the xml part, if I understand correctly? If so, do you think it would be possible to briefly document how to make the automator script? Even if this is most likely going to be dependent on the automator version, etc explaining the main steps may help to make it again if necessary.

**Comment by douglowe** [comment]
Thanks for the new image - that is definitely more readable.

Yes - probably the best way to fix things if OSX breaks it is to rerun automator. I can add some brief notes on how to step through automator - would you like these as comments in the script, or would a page on the repository wiki be better?

**Comment by ericpre** [comment]
I think that having the notes in the code directly is better, we don't use much the wiki (generally, wiki on github doesn't have very good visibility and for most project I came across this is not used much neither).

Do you think it would sensible to have the automator script as a separate file? For future update but also if it can be imported to automator?

**Comment by douglowe** [comment]
I've added some notes on how to create a script in automator - please let me know if they read okay (or if I've missed any steps).

Having the automator scripts as separate files could be useful - though in order to accomodate the directory style automator expects the layout is a bit abstract.

I've set this up on another branch so you can see how it would look: [https://github.com/UoMResearchIT/start_jupyter_cm/tree/workflow_prototype](https://github.com/UoMResearchIT/start_jupyter_cm/tree/workflow_prototype). If you prefer this layout then I'll merge this branch with master.

**Comment by ericpre** [comment]
The instructions are good.

> I've set this up on another branch so you can see how it would look: https://github.com/UoMResearchIT/start_jupyter_cm/tree/workflow_prototype. If you prefer this layout then I'll merge this branch with master.

I have checked it and it works fine too. I would prefer this one, because it should be more easy to understand where the two files come from when we update these. @francisco-dlp, any opinion?

**Comment by francisco-dlp** [comment]
I  agree with @ericpre, this version seems better to maintain. @ericpre, I suggest merging and releasing.

**Comment by douglowe** [comment]
Cool. I've merged the workflow_prototype branch into master - it should be ready for you to merge now.

**Pull request merged**
